# 01. k-최근접 이웃 (k-NN)
작성일 : 2020-09-28
- - -

**K-최근접 이웃**(k-NN, k-Nearest Neighbors) 알고리즘은 **특정공간내에서 입력과 제일 근접한 k개의 요소를 찾아, 더 많이 일치하는 것으로 분류하는 알고리즘**이다.

## 1.1 원리

|사회적인 관점|공간적인 관점|
|--|--|
|- 비슷한 사람끼리 모이는 성질 <br> - 비슷한 취향의 사람끼리 모여서 동호회를 만든다. <br> - 비슷한 부류의 계층의 사람끼리 친분을 맺기도 한다. | - 가구점 <br> - 맛집 <br> - 한약방| 

<br>

## 1.2 거리계산 알고리즘
- 유클리드 거리 (Euclidean distance)
- 두 점 사이의 거리

```
1. 수직선

----|------------|---------
    a            b  
    큰값 - 작은값
    |b - a|

2. 평면 

    p(x1,x2) q(x2,y2)
    math.sqrt((x1-x2)**2 + (y1-y2) **2)
```



## 1.3 k-NN 알고리즘
- 유클리드 거리계산을 해서 오름차순으로 정렬
- k = 3일 경우 가장 가까운 거리의 3개 선택, 이를 다수결로 분류
- 가장 중요한 것은 k값. k값을 어떻게 주느냐에 따라 분류가 달라진다.
- k값은 홀수로 하는 것이 일반적

![knn](https://miro.medium.com/max/810/0*QyWp7J6eSz0tayc0.png)

[문제1] 거리계산을 한 후 가장 가까운 3개만 추출해주세요.

In [ ]:
point = [2,1]
pointlst = [(1,1),(1,0),(2,0),(0,1),(2,2),(1,5),(2,3)]

In [ ]:
import math
dislst = []
for i in pointlst:
    x, y = i
    dis = math.sqrt((2 - x)**2 + (1 - y)**2)
    dislst.append(dis)

In [ ]:
num = 0
for i in dislst:
    if i == min(dislst):
        print(pointlst[num])
    num += 1

(1, 1)
(2, 0)
(2, 2)


<br>

[해설1]

In [ ]:
import numpy as np
import operator

result = []
for i in pointlst:
    result.append(np.sqrt((point[0] - i[0])**2 + ((point[1] - i[1])**2)))

In [ ]:
result.sort()   # 리스트에 정렬하여 적용
sorted(result)  # 정렬한 값 미리보기

[1.0, 1.0, 1.0, 1.4142135623730951, 2.0, 2.0, 4.123105625617661]

In [ ]:
for i in np.argsort(result)[:3]: # 데이터 정렬하여 인덱스 반환
    print(pointlst[i])

(1, 1)
(1, 0)
(2, 0)


### 참고 | 자료형 별 연산


#### (1) list
리스트 형식으로 연산을 하기 위해서는 인덱싱 필요

In [ ]:
point[0] - pointlst[0][0]

1

In [ ]:
point[1] - pointlst[0][1]

0

#### (2) array
array로 변환할 경우

In [ ]:
np.array(point) - np.array(pointlst)

array([[ 1,  0],
       [ 1,  1],
       [ 0,  1],
       [ 2,  0],
       [ 0, -1],
       [ 1, -4],
       [ 0, -2]])

##### broadcasting
shape이 맞지 않을 경우 자동으로 broadcasting 작업이 돌아간다.

In [ ]:
np.array(point).shape

(2,)

In [ ]:
np.array(pointlst).shape

(7, 2)

In [ ]:
point1 = np.array(point)
point2 = np.array(pointlst)
dist = np.sqrt(np.sum(pow(point1 - point2, 2), axis = 1))
dist

array([1.        , 1.41421356, 1.        , 2.        , 1.        ,
       4.12310563, 2.        ])

In [ ]:
for i in dist.argsort()[:3]:
    print(pointlst[i])

(1, 1)
(2, 0)
(2, 2)


#### (3) dictionary

In [ ]:
dic = {}
for i in pointlst:
    d = np.sqrt(sum((np.array(point) - np.array(i))**2))
    dic[i] = d
dic

{(0, 1): 2.0,
 (1, 0): 1.4142135623730951,
 (1, 1): 1.0,
 (1, 5): 4.123105625617661,
 (2, 0): 1.0,
 (2, 2): 1.0,
 (2, 3): 2.0}

In [ ]:
import operator
sort_dic = sorted(dic.items(),key = operator.itemgetter(1))
sort_dic

[((1, 1), 1.0),
 ((2, 0), 1.0),
 ((2, 2), 1.0),
 ((1, 0), 1.4142135623730951),
 ((0, 1), 2.0),
 ((2, 3), 2.0),
 ((1, 5), 4.123105625617661)]

In [ ]:
res = []
for key in sort_dic:
    if len(res) < 3:
        res.append(key[0])
res

[(1, 1), (2, 0), (2, 2)]

<br/>  

### k-NN의 원리 이해
```
 재료   단맛   아삭한맛   종류     거리
-------------------------------------------------------
포도     8      5      과일    sqrt((6-8)**2 + (4-5)**2) = 2.23606797749979
콩      3      7      채소    sqrt((6-3)**2 + (4-7)**2) = 4.242640687119285
견과     3      6     단백질    sqrt((6-3)**2 + (4-6)**2) = 3.605551275463989
오렌지    7      3      과일    sqrt((6-7)**2 + (4-3)**2) = 1.4142135623730951
```

- 토마토 : 단맛 6, 아삭한맛 4

- k = 1
  - 오렌지와 토마토 거리는 1.4로 가까운 이웃하여 과일로 분류

- k = 3
  - 오렌지, 포도, 견과 세가지 사이에서 다수결로 정한다.
  - 종류가 과일, 과일, 단백질 중에 다수결로 과일로 분류한다.  
<br/> 


[문제2] food.csv 읽어들인 후 토마토 단맛 6, 아삭한맛 4를 이용해서 거리계산한 dist 컬럼에 입력해주세요. dist 컬럼의 값을 오름차순으로 rank 컬럼에 추가해주세요.


In [ ]:
import pandas as pd
food = pd.read_csv("c:/data/food.csv")
food

ingredient  sweetness  crunchiness       class
0        apple         10            9      Fruits
1        bacon          1            4    Proteins
2       banana         10            1      Fruits
3       carrot          7           10  Vegetables
4       celery          3           10  Vegetables
5       cheese          1            1    Proteins
6     cucumber          2            8  Vegetables
7         fish          3            1    Proteins
8        grape          8            5      Fruits
9   green bean          3            7  Vegetables
10     lettuce          1            9  Vegetables
11        nuts          3            6    Proteins
12      orange          7            3      Fruits
13        pear         10            7      Fruits
14      shrimp          2            3    Proteins

- feature : 예측, 분류를 하기 위해서 사용되는 입력변수. 독립변수, 설명변수라고도 한다.  
종속변수에 영향을 주는 변수들 (sweetness, crunchiness)
- 종속변수 : 영향을 받는 변수 (class) → 레이블

(1) Series로 풀기

In [ ]:
tomato = [6,4]
dist = ((tomato[0] - food.sweetness)**2 + (tomato[1] - food.crunchiness)**2)**(1/2)
type(dist)

pandas.core.series.Series

In [ ]:
food1 = pd.read_csv("c:/data/food.csv")
data = pd.merge(food1, pd.DataFrame({"dist":dist}),left_index = True, right_index=True)
data.sort_values(by = "dist", ascending = True)

ingredient  sweetness  crunchiness       class      dist
12      orange          7            3      Fruits  1.414214
8        grape          8            5      Fruits  2.236068
11        nuts          3            6    Proteins  3.605551
14      shrimp          2            3    Proteins  4.123106
7         fish          3            1    Proteins  4.242641
9   green bean          3            7  Vegetables  4.242641
1        bacon          1            4    Proteins  5.000000
2       banana         10            1      Fruits  5.000000
13        pear         10            7      Fruits  5.000000
6     cucumber          2            8  Vegetables  5.656854
5       cheese          1            1    Proteins  5.830952
3       carrot          7           10  Vegetables  6.082763
0        apple         10            9      Fruits  6.403124
4       celery          3           10  Vegetables  6.708204
10     lettuce          1            9  Vegetables  7.071068

In [ ]:
data['rank'] = data['dist'].rank(ascending = True, method = 'dense')
data[data['rank'] <= 3]

ingredient  sweetness  crunchiness     class      dist  rank
8       grape          8            5    Fruits  2.236068   2.0
11       nuts          3            6  Proteins  3.605551   3.0
12     orange          7            3    Fruits  1.414214   1.0

In [ ]:
x = data.loc[data['rank'] <= 3, 'class'].value_counts()[data.loc[data['rank'] <= 3, 'class'].value_counts() == data.loc[data['rank'] <= 3, 'class'].value_counts().max()]
x

Fruits    2
Name: class, dtype: int64

In [ ]:
x.index[0]

'Fruits'

(2) array로 풀기

In [ ]:
food = pd.read_csv('c:/data/food.csv')
x_train = np.array(food2.iloc[:,1:3])
x_train

array([[10,  9],
       [ 1,  4],
       [10,  1],
       [ 7, 10],
       [ 3, 10],
       [ 1,  1],
       [ 2,  8],
       [ 3,  1],
       [ 8,  5],
       [ 3,  7],
       [ 1,  9],
       [ 3,  6],
       [ 7,  3],
       [10,  7],
       [ 2,  3]])

In [ ]:
x_train.shape

(15, 2)

In [ ]:
y = np.array([[6,4]])
y.shape

(1, 2)

In [ ]:
x_train - y

array([[ 4,  5],
       [-5,  0],
       [ 4, -3],
       [ 1,  6],
       [-3,  6],
       [-5, -3],
       [-4,  4],
       [-3, -3],
       [ 2,  1],
       [-3,  3],
       [-5,  5],
       [-3,  2],
       [ 1, -1],
       [ 4,  3],
       [-4, -1]])

In [ ]:
food['dist'] = np.sqrt(np.sum(pow(x_train-y,2), axis = 1))
food

ingredient  sweetness  crunchiness       class      dist
0        apple         10            9      Fruits  6.403124
1        bacon          1            4    Proteins  5.000000
2       banana         10            1      Fruits  5.000000
3       carrot          7           10  Vegetables  6.082763
4       celery          3           10  Vegetables  6.708204
5       cheese          1            1    Proteins  5.830952
6     cucumber          2            8  Vegetables  5.656854
7         fish          3            1    Proteins  4.242641
8        grape          8            5      Fruits  2.236068
9   green bean          3            7  Vegetables  4.242641
10     lettuce          1            9  Vegetables  7.071068
11        nuts          3            6    Proteins  3.605551
12      orange          7            3      Fruits  1.414214
13        pear         10            7      Fruits  5.000000
14      shrimp          2            3    Proteins  4.123106

(3) Counter 이용

In [ ]:
food['rank'] = food['dist'].rank(ascending=True, method = 'dense')
food[food['rank'] <= 3]['class']

8       Fruits
11    Proteins
12      Fruits
Name: class, dtype: object

In [ ]:
from collections import Counter
Counter(food[food['rank'] <= 3]['class']).most_common(1) # counter 값 중 가장 빈도가 높은 n개만 출력하는 것.

[('Fruits', 2)]

In [ ]:
Counter(food[food['rank'] <= 3]['class']).most_common(1)[0][0]

'Fruits'

<br/>  