# 실습 | 붓꽃 · 유방암
작성일 : 2020-09-29

---

## 01　붓꽃 (iris)

```{admonition} Iris
:class: tip
아이리스는 통계학자인 피셔(Fisher)가 소개한 데이터로, 붓꽃의 3가지 종(setosa, versicolor, virginica)에 대해 꽃받침(sepal)과 꽃잎(petal)의 길이를 정리한 데이터다. 이 데이터는 R과 sklearn 패키지에 기본으로 내장되어 있고, 이해하기 쉬우며 크기가 작고 기계 학습에서 인기 있는 분야 중 하나인 분류(Classification)에 적합한 데이터다.
```

### [문제5]
붓꽃 데이터입니다. kNN으로 분류해주세요.

- `SepalLength` : 꽃받침의 길이
- `SepalWidth` : 꽃받침의 폭 (너비)
- `PetalLength` : 꽃잎의 길이
- `PetalWidth` : 꽃잎의 너비
- `Name` : 붓꽃 이름  
<br/>

```
SepalLength  : 2.0
SepalWidth   : 7.0
PetalLength  : 1.0
PetalWidth   : 0.1
```

#### 데이터 불러오기

In [2]:
import pandas as pd
iris = pd.read_csv("c:/data/iris.csv")
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Name         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [3]:
iris.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
iris['Name'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

#### kNN을 이용한 분류

In [6]:
import numpy as np

x_train = np.array(iris.iloc[:,0:4])
x_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
test = np.array([[2.0, 7.0, 1.0, 0.1],
                 [5.9, 3. , 5.1, 1.8]])
test

array([[2. , 7. , 1. , 0.1],
       [5.9, 3. , 5.1, 1.8]])

In [8]:
label = iris['Name']

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(x_train, label)
clf.predict(test)

array(['Iris-setosa', 'Iris-virginica'], dtype=object)

### 학습 및 테스트 데이터 만들기

In [12]:
X = iris.iloc[:,0:4]
X

SepalLength  SepalWidth  PetalLength  PetalWidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [13]:
Y = iris.iloc[:,-1]
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Name, Length: 150, dtype: object

In [14]:
from sklearn.model_selection import train_test_split # 학습 데이터 균등하게 나누기
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [15]:
X_train

SepalLength  SepalWidth  PetalLength  PetalWidth
140          6.7         3.1          5.6         2.4
4            5.0         3.6          1.4         0.2
95           5.7         3.0          4.2         1.2
116          6.5         3.0          5.5         1.8
52           6.9         3.1          4.9         1.5
..           ...         ...          ...         ...
29           4.7         3.2          1.6         0.2
77           6.7         3.0          5.0         1.7
10           5.4         3.7          1.5         0.2
148          6.2         3.4          5.4         2.3
136          6.3         3.4          5.6         2.4

[120 rows x 4 columns]

In [16]:
Y_train

140     Iris-virginica
4          Iris-setosa
95     Iris-versicolor
116     Iris-virginica
52     Iris-versicolor
            ...       
29         Iris-setosa
77     Iris-versicolor
10         Iris-setosa
148     Iris-virginica
136     Iris-virginica
Name: Name, Length: 120, dtype: object

In [17]:
X_test

SepalLength  SepalWidth  PetalLength  PetalWidth
24           4.8         3.4          1.9         0.2
80           5.5         2.4          3.8         1.1
15           5.7         4.4          1.5         0.4
115          6.4         3.2          5.3         2.3
53           5.5         2.3          4.0         1.3
118          7.7         2.6          6.9         2.3
50           7.0         3.2          4.7         1.4
112          6.8         3.0          5.5         2.1
67           5.8         2.7          4.1         1.0
9            4.9         3.1          1.5         0.1
94           5.6         2.7          4.2         1.3
0            5.1         3.5          1.4         0.2
19           5.1         3.8          1.5         0.3
54           6.5         2.8          4.6         1.5
41           4.5         2.3          1.3         0.3
48           5.3         3.7          1.5         0.2
25           5.0         3.0          1.6         0.2
59           5.2         2.7          3.9         1.4
81           5.5         2.4          3.7         1.0
92           5.8         2.6          4.0         1.2
37           4.9         3.1          1.5         0.1
100          6.3         3.3          6.0         2.5
63           6.1         2.9          4.7         1.4
120          6.9         3.2          5.7         2.3
32           5.2         4.1          1.5         0.1
6            4.6         3.4          1.4         0.3
7            5.0         3.4          1.5         0.2
76           6.8         2.8          4.8         1.4
1            4.9         3.0          1.4         0.2
57           4.9         2.4          3.3         1.0

In [18]:
Y_test

24         Iris-setosa
80     Iris-versicolor
15         Iris-setosa
115     Iris-virginica
53     Iris-versicolor
118     Iris-virginica
50     Iris-versicolor
112     Iris-virginica
67     Iris-versicolor
9          Iris-setosa
94     Iris-versicolor
0          Iris-setosa
19         Iris-setosa
54     Iris-versicolor
41         Iris-setosa
48         Iris-setosa
25         Iris-setosa
59     Iris-versicolor
81     Iris-versicolor
92     Iris-versicolor
37         Iris-setosa
100     Iris-virginica
63     Iris-versicolor
120     Iris-virginica
32         Iris-setosa
6          Iris-setosa
7          Iris-setosa
76     Iris-versicolor
1          Iris-setosa
57     Iris-versicolor
Name: Name, dtype: object

### kNN을 이용한 테스트 데이터 분류

In [19]:
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, Y_train)
clf.predict(X_test)

array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor'], dtype=object)

### 정확도

In [20]:
clf.score(X_test, Y_test) # 정확도 96%

1.0

## 02　유방암 (Breast Cancer)

```{admonition} Breast Cancer
:class: tip
https://archive.ics.uci.edu/ml/index.php

- 위스콘신대학의 연구원들의 자료
- 유방 종양의 미세침 흡인물 디지털 이미지에서 측정한 값이며 이 값은 디지털 이미지에 나타난 세포 핵의 - 특징이다.
- 암 조직 검사에 대한 관측값은 569개, 변수(속성) 32
- 식별 숫자, 암진단 여부 (악성(Malignant), 양성(Benign)), 30개 수치 측정치
```


### [문제7]
유방암 데이터 입니다. kNN 알고리즘을 이용해서 훈련 데이터셋, 테스트데이터셋을 이용해서 분류가 잘 되는지 확인하세요.


```{admonition} 세포핵의 모양과 크기 관련된 10개 특성 
:class: note
- radius (반지름)
- texture (질감)
- perimeter (둘레)
- area (넓이)
- smoothness (매끄러움)
- compactness (조밀성)
- concavity (오목함)
- concave points (오목점)
- symmetry (대칭성)
- fractal dimension (프랙탈 차원)
```


#### 데이터 불러오기

In [21]:
data = pd.read_csv("c:/data/wisc_bc_data.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 569 non-null    int64  
 1   diagnosis          569 non-null    object 
 2   radius_mean        569 non-null    float64
 3   texture_mean       569 non-null    float64
 4   perimeter_mean     569 non-null    float64
 5   area_mean          569 non-null    float64
 6   smoothness_mean    569 non-null    float64
 7   compactness_mean   569 non-null    float64
 8   concavity_mean     569 non-null    float64
 9   points_mean        569 non-null    float64
 10  symmetry_mean      569 non-null    float64
 11  dimension_mean     569 non-null    float64
 12  radius_se          569 non-null    float64
 13  texture_se         569 non-null    float64
 14  perimeter_se       569 non-null    float64
 15  area_se            569 non-null    float64
 16  smoothness_se      569 non

#### 표준화

In [22]:
from sklearn.preprocessing import scale

In [77]:
X = scale(data.iloc[:,2:])
X

array([[-0.51329651, -1.60559452, -0.54037561, ..., -0.31513306,
        -0.11932056, -0.89972108],
       [-1.00180093, -0.07903849, -0.93456583, ..., -0.53820271,
         0.06348865, -0.44752801],
       [-0.87683468, -0.57237672, -0.8670139 , ..., -0.61357437,
         0.15731992, -0.28460551],
       ...,
       [ 0.32738551,  0.72612674,  0.28631171, ...,  0.12171802,
         0.44366709,  0.7633076 ],
       [ 0.11437486, -1.23559085,  0.07788929, ..., -0.11733956,
        -0.47685008, -0.32395074],
       [ 2.05703196, -0.97495933,  2.03195239, ...,  1.24848623,
        -0.27624528,  0.15040866]])

In [78]:
Y = data.iloc[:,1]
Y

0      B
1      B
2      B
3      B
4      B
      ..
564    B
565    B
566    M
567    B
568    M
Name: diagnosis, Length: 569, dtype: object

#### 학습 및 테스트 데이터 만들기

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

In [89]:
X_train

array([[-1.53177142, -0.57004965, -1.51164053, ..., -1.74506282,
        -0.73731275,  0.26068613],
       [-0.30596615, -1.26816979, -0.38138144, ..., -1.2072594 ,
        -1.2841226 , -1.00556529],
       [-0.51329651, -1.60559452, -0.54037561, ..., -0.31513306,
        -0.11932056, -0.89972108],
       ...,
       [-1.29518759, -0.78646689, -1.30816094, ..., -0.64539796,
        -0.2325652 , -0.12002053],
       [-0.07023436, -0.72829022, -0.14824491, ..., -1.0542321 ,
        -0.58038803, -0.98173649],
       [-0.9052361 , -0.1628129 , -0.88884471, ..., -0.54414108,
        -1.05116219, -0.36717508]])

In [90]:
X_test

array([[-0.5331775 ,  0.73310794, -0.56797305, ..., -0.78045787,
         0.32233355, -0.10616658],
       [ 0.56879758, -0.32803467,  0.61912852, ...,  1.09317493,
         2.21513686,  2.18084421],
       [ 0.14561642, -0.94238039,  0.15656258, ...,  0.38209284,
         0.40484036,  0.04345613],
       ...,
       [-0.52749722, -0.3187264 , -0.5584993 , ..., -0.29366356,
         0.89664566, -0.83045131],
       [ 0.23650097, -0.04413248,  0.20846223, ...,  0.52217753,
         0.09907982,  0.04290197],
       [-1.34347001,  0.55625084, -1.32710844, ..., -1.35465286,
        -0.84893962,  0.44965407]])

In [91]:
Y_train

136    B
30     B
0      B
533    M
415    M
      ..
538    B
85     B
409    B
395    B
22     B
Name: diagnosis, Length: 398, dtype: object

In [92]:
Y_test

268    B
383    M
83     B
476    B
37     B
      ..
195    M
84     B
33     B
478    B
242    B
Name: diagnosis, Length: 171, dtype: object

#### kNN을 이용한 분류

In [93]:
clf = KNeighborsClassifier(n_neighbors=21)
clf.fit(X_train, Y_train)
clf.predict(X_test)

array(['B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B',
       'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B',
       'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'M', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'B',
       'B', 'B'], dtype=object)

#### 정확도

In [94]:
clf.score(X_test, Y_test)

0.9824561403508771

#### 예측과 일치하지 않는 데이터

In [110]:
idx = Y_test[Y_test != clf.predict(X_test)].index
data.loc[idx]

id diagnosis  ...  symmetry_worst  dimension_worst
200  855133         M  ...          0.1565          0.05504
481  862548         M  ...          0.2718          0.09353
243  888264         M  ...          0.2452          0.06515

[3 rows x 32 columns]

#### 혼동행렬

In [96]:
pd.crosstab(Y_test, clf.predict(X_test)) # 교차표, 혼동행렬

col_0        B   M
diagnosis         
B          112   0
M            3  56

- 112개, 56개는 정답, 3개는 오답