# Feature Scaling
작성일 : 2020-09-29

---

## Feature Scaling
서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업

### 표준화 (Standardization)
평균은 0, 표준편차 1인 표준정규분포를 가진 값으로 변환

```
   관측값 - 평균
   ----------
     표준편차
```

In [2]:
import numpy as np
x = np.arange(9, dtype = np.float) - 3
x

array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [3]:
x.shape

(9,)

In [4]:
x.reshape(9,1) # 행의 수를 알고 있을 경우
np.reshape(x,(9,1))

array([[-3.],
       [-2.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.]])

In [5]:
x = x.reshape(-1,1) # 열은 고정, 행은 가변일 경우 -1
x

array([[-3.],
       [-2.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.]])

In [6]:
x = np.vstack([x,[100]]) # 열 이어붙이기
x

array([[ -3.],
       [ -2.],
       [ -1.],
       [  0.],
       [  1.],
       [  2.],
       [  3.],
       [  4.],
       [  5.],
       [100.]])

In [8]:
import pandas as pd
pd.DataFrame(x).describe()

0
count   10.000000
mean    10.900000
std     31.412842
min     -3.000000
25%     -0.750000
50%      1.500000
75%      3.750000
max    100.000000

In [9]:
# 표준화
y = (x - np.mean(x)) / np.std(x)
y

array([[-0.46642982],
       [-0.43287372],
       [-0.39931762],
       [-0.36576152],
       [-0.33220541],
       [-0.29864931],
       [-0.26509321],
       [-0.23153711],
       [-0.197981  ],
       [ 2.98984872]])

In [10]:
pd.DataFrame(y).describe()

0
count  1.000000e+01
mean  -4.440892e-17
std    1.054093e+00
min   -4.664298e-01
25%   -3.909286e-01
50%   -3.154274e-01
75%   -2.399261e-01
max    2.989849e+00

### 정규화 (Normalization)
최소값과 최대값을 사용해서 0 ~ 1 사이의 데이터로 변환

```
       x - x.min()
    -----------------
    x.max() - x.min()
```

In [11]:
(x - x.min()) / (x.max() - x.min())

array([[0.        ],
       [0.00970874],
       [0.01941748],
       [0.02912621],
       [0.03883495],
       [0.04854369],
       [0.05825243],
       [0.06796117],
       [0.0776699 ],
       [1.        ]])

### Feature Scaling 패키지

#### 표준화

In [12]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()

In [13]:
r = s.fit_transform(x)
r

array([[-0.46642982],
       [-0.43287372],
       [-0.39931762],
       [-0.36576152],
       [-0.33220541],
       [-0.29864931],
       [-0.26509321],
       [-0.23153711],
       [-0.197981  ],
       [ 2.98984872]])

In [14]:
np.mean(r)

0.0

In [15]:
np.std(r)

1.0

In [16]:
from sklearn.preprocessing import scale
scale(x)

array([[-0.46642982],
       [-0.43287372],
       [-0.39931762],
       [-0.36576152],
       [-0.33220541],
       [-0.29864931],
       [-0.26509321],
       [-0.23153711],
       [-0.197981  ],
       [ 2.98984872]])

In [17]:
np.mean(scale(x))

0.0

In [18]:
np.std(scale(x))

1.0

#### 정규화

In [19]:
from sklearn.preprocessing import MinMaxScaler
m = MinMaxScaler()
m.fit_transform(x)

array([[0.        ],
       [0.00970874],
       [0.01941748],
       [0.02912621],
       [0.03883495],
       [0.04854369],
       [0.05825243],
       [0.06796117],
       [0.0776699 ],
       [1.        ]])

In [20]:
from sklearn.preprocessing import minmax_scale
minmax_scale(x)

array([[0.        ],
       [0.00970874],
       [0.01941748],
       [0.02912621],
       [0.03883495],
       [0.04854369],
       [0.05825243],
       [0.06796117],
       [0.0776699 ],
       [1.        ]])

#### bmi 문제 다시 풀기

In [23]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

bmi = pd.read_csv("c:/data/bmi.csv")
bmi

height  weight   label
0         142      62     fat
1         142      73     fat
2         177      61  normal
3         187      48    thin
4         153      60     fat
...       ...     ...     ...
19995     122      58     fat
19996     193      69  normal
19997     193      37    thin
19998     195      51    thin
19999     163      67  normal

[20000 rows x 3 columns]

In [24]:
x_train = np.array(bmi.iloc[:,0:2])
label = bmi['label']
y = np.array([[178, 71]])

##### 표준화

In [25]:
pd.DataFrame(x_train).describe()

0             1
count  20000.000000  20000.000000
mean     159.927200     57.535000
std       23.342096     13.285259
min      120.000000     35.000000
25%      140.000000     46.000000
50%      160.000000     58.000000
75%      180.000000     69.000000
max      200.000000     80.000000

In [26]:
x_train

array([[142,  62],
       [142,  73],
       [177,  61],
       ...,
       [193,  37],
       [195,  51],
       [163,  67]])

In [27]:
x_train_scale = scale(x_train)
x_train_scale

array([[-0.76803935,  0.3360952 ],
       [-0.76803935,  1.16410127],
       [ 0.73143504,  0.26082192],
       ...,
       [ 1.41690904, -1.5457368 ],
       [ 1.5025933 , -0.49191088],
       [ 0.13164528,  0.71246159]])

In [28]:
pd.DataFrame(x_train_scale).describe()

0             1
count  2.000000e+04  2.000000e+04
mean   7.332052e-17  2.467693e-16
std    1.000025e+00  1.000025e+00
min   -1.710566e+00 -1.696283e+00
25%   -8.537236e-01 -8.682773e-01
50%    3.118907e-03  3.500208e-02
75%    8.599614e-01  8.630082e-01
max    1.716804e+00  1.691014e+00

In [29]:
y = np.array([[170, 91]])
y

array([[170,  91]])

In [30]:
y_scale = np.array([[(y[0][0] - 159.927200) / 23.342096, (y[0][1] - 57.535000) / 13.285259]])
y_scale

array([[0.43152937, 2.51895729]])

In [31]:
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(x_train_scale, label)
clf.predict(y_scale)[0]

'fat'

##### 정규화

In [32]:
pd.DataFrame(x_train).describe()

0             1
count  20000.000000  20000.000000
mean     159.927200     57.535000
std       23.342096     13.285259
min      120.000000     35.000000
25%      140.000000     46.000000
50%      160.000000     58.000000
75%      180.000000     69.000000
max      200.000000     80.000000

In [33]:
x_train_minmax = minmax_scale(x_train)
x_train_minmax

array([[0.275     , 0.6       ],
       [0.275     , 0.84444444],
       [0.7125    , 0.57777778],
       ...,
       [0.9125    , 0.04444444],
       [0.9375    , 0.35555556],
       [0.5375    , 0.71111111]])

In [34]:
pd.DataFrame(x_train_minmax).describe()

0             1
count  20000.000000  20000.000000
mean       0.499090      0.500778
std        0.291776      0.295228
min        0.000000      0.000000
25%        0.250000      0.244444
50%        0.500000      0.511111
75%        0.750000      0.755556
max        1.000000      1.000000

In [35]:
y_minmax = np.array([[(y[0][0] - 120) / (200 - 120), (y[0][1] - 35) / (80 - 35)]])
y_minmax

array([[0.625     , 1.24444444]])

In [36]:
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(x_train_minmax, label)
clf.predict(y_minmax)[0]

'fat'