# sklearn.naive_bayes

## 2.11 sklearn

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [ ]:
survey = pd.read_csv("naive_survey.csv", header = None, names = ['sentence', 'class'])
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   sentence  15 non-null     object
 1   class     15 non-null     object
dtypes: object(2)
memory usage: 368.0+ bytes


In [ ]:
survey['class'].map({"긍정" : 1, "부정" : 0})

0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     0
10    0
11    0
12    1
13    1
14    1
Name: class, dtype: int64

In [ ]:
survey['class'] = survey['class'].map({"긍정" : 1, "부정" : 0})
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   sentence  15 non-null     object
 1   class     15 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 368.0+ bytes


In [ ]:
cv = CountVectorizer()
x_train = cv.fit_transform(survey['sentence'])
x_train

<15x39 sparse matrix of type '<class 'numpy.int64'>'
	with 53 stored elements in Compressed Sparse Row format>

In [ ]:
y_train = survey['class']
encode_cv = x_train.toarray()
encode_cv.shape

(15, 39)

In [ ]:
encode_cv

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
# 인코딩된 벡터를 실제 단어로 변환
cv.inverse_transform(encode_cv[0:2])

[array(['좋아', '홍길동은'], dtype='<U5'), array(['강아지는', '무지', '좋아'], dtype='<U5')]

In [ ]:
# 벡터로 변환되어 있는 단어를 확인
cv.get_feature_names()

['강아지는',
 '강아지야',
 '공기가',
 '난다',
 '날이',
 '날이야',
 '너무',
 '놀거야',
 '마치고',
 '많아서',
 '맑아서',
 '무지',
 '밝게',
 '비가',
 '사람이',
 '수업',
 '수업이',
 '없어',
 '오늘',
 '오니',
 '이쁜',
 '인사해주니',
 '재미없어',
 '좋다',
 '좋아',
 '지하철에',
 '지하철에서',
 '질서는',
 '짜증난다',
 '짜증낸다',
 '짜증스러운',
 '짜증이',
 '친구가',
 '하늘이',
 '하루가',
 '하루는',
 '행복하다',
 '홍길동은',
 '홍길동이랑']

In [ ]:
x_train

<15x39 sparse matrix of type '<class 'numpy.int64'>'
	with 53 stored elements in Compressed Sparse Row format>

In [ ]:
y_train = survey['class']
y_train

0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     0
10    0
11    0
12    1
13    1
14    1
Name: class, dtype: int64

In [ ]:
survey['class']

0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     0
10    0
11    0
12    1
13    1
14    1
Name: class, dtype: int64

In [ ]:
nb = MultinomialNB()
nb.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
x_test = cv.transform(survey['sentence'])
x_test

<15x39 sparse matrix of type '<class 'numpy.int64'>'
	with 53 stored elements in Compressed Sparse Row format>

In [ ]:
y_predict = nb.predict(x_test)
y_predict

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1])

In [ ]:
accuracy_score(survey['class'], y_predict)

1.0

In [ ]:
txt = pd.Series("함께 살고 있는 강아지가 너무 좋아")
x_test = cv.transform(txt)
nb.predict(x_test)

array([1])

In [ ]:
from konlpy.tag import Okt

In [ ]:
pos_tagger = Okt()

In [ ]:
survey = pd.read_csv("naive_survey.csv", header = None, names = ['sentence','class'])
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   sentence  15 non-null     object
 1   class     15 non-null     object
dtypes: object(2)
memory usage: 368.0+ bytes


In [ ]:
contents_token = [pos_tagger.morphs(i) for i in survey['sentence']]

In [ ]:
contents_vectorize = []

for i in contents_token:
  txt = ''
  for w in i:
    txt = txt + " " + w
  contents_vectorize.append(txt)

contents_vectorize

[' 홍길동 은 좋아',
 ' 강아지 는 무지 좋아',
 ' 수업 이 재미없어',
 ' 홍길동 은 이쁜 강아지 야',
 ' 난 수업 마치 고 홍길동 이랑 놀거야',
 ' 오늘 하루 는 너무 짜증스러운 날 이야',
 ' 하루 가 너무 짜증스러운 날 이야',
 ' 날 이 맑아서 좋아',
 ' 오늘 지하철 에 사람 이 너무 많아서 짜증 이 난다',
 ' 지하철 에서 질서 는 너무 없어 짜증 이 난다',
 ' 비 가 오니 짜증난다',
 ' 친구 가 짜증 낸다',
 ' 하늘 이 맑아서 행복하다',
 ' 공기 가 맑아서 좋다',
 ' 밝게 인사 해주니 행복하다']